export const HOME_STACK = {
  STACK: 'HOME_STACK',
  MAIN: 'HOME_MAIN',
  SEARCH: 'HOME_SEARCH',
  FAVORITES: 'HOME_FAVORITES',
  RECENT: 'HOME_RECENT',
  RECOMMENDED: 'HOME_RECOMMENDED',
  CATEGORIES: 'HOME_CATEGORIES',
  CATEGORY: 'HOME_CATEGORY',
  CATEGORY_DETAIL: 'HOME_CATEGORY_DETAIL',
};

export const SETTINGS_STACK = {
  STACK: 'SETTINGS_STACK',
  MAIN: 'SETTINGS_MAIN',
  PROFILE: 'SETTINGS_PROFILE',
  PASSWORD: 'SETTINGS_PASSWORD',
  NOTIFICATIONS: 'SETTINGS_NOTIFICATIONS',
  ABOUT: 'SETTINGS_ABOUT',
};
